# Generated by Django 5.0.6 on 2024-07-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='student.student', verbose_name='Students'),
        ),
        migrations.DeleteModel(
            name='StudentShip',
        ),
    ]
